import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
 
      </main>

      <footer className={styles.footer}>
        <p>Powered by<a href="https://i.kym-cdn.com/entries/icons/original/000/030/873/Screenshot_20.jpg" target="_blank"><strong> swag</strong></a></p>
      </footer>
    </div>
  )
}
