import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import Chat from '../components/chat';

export default function Home() {
  const [authed, setAuthed] = useState(false);
  var swagVersion = 3
  if (!authed) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            SwagChat v{swagVersion}
          </h1>
          <br></br>
          <input type="input" hidden></input>
          <h2>The Swaggest of all Chats</h2>
          <button onClick={()=> {
            setAuthed(true)
          }}>Click here to begin Authentication</button>
        </main>
  
        <footer className={styles.footer}>
          <p>
          <a
            href="https://i.kym-cdn.com/entries/icons/original/000/030/873/Screenshot_20.jpg"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <strong>
              Swag
            </strong>
          </a>
          </p>
  
        </footer>
      </div>
    )
  } else {
    return <><Chat/></>
  }
  function authenticateUser(username) {
    console.log('sheesh ' + username)
  }  
}

